<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация и регистрация</title>
    <link rel="stylesheet" href="/css/login.css">
</head>
<body>

<!-- Форма авторизации -->

<form action="" method="POST">
    <label>Логин</label>
    <input type="text" name="email-phone" placeholder="Введите свой E-mail или телефон">
    <label>Пароль</label>
    <input type="password" name="password" placeholder="Введите пароль">
    <button type="submit" class="login-btn">Войти</button>
    <p>
        У вас нет аккаунта? - <a href="/signup">зарегистрируйтесь</a>!
    </p>
</form>
</body>
</html>