<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Мой профиль</title>
    <link rel="stylesheet" href="/css/profile.css">
</head>
<body>
<div class="back">
    <a href="/" type="button">
        Вернуться назад
    </a>
</div>
<div class="profile">
    <form action="/profile/edit" method="POST">
        <label for="name">Имя</label>
        <label for="name" style="color: #4b1010">
            <?php
            if (isset($errors['name'])) {
                echo $errors['name'];
            }
            ?>
        </label>
        <input id="name" type="text" name="name" placeholder="Введите имя" value="<?php echo $user->getName() ?>">

        <label for="phone">Телефон</label>
        <label for="phone" style="color: #4b1010">
            <?php
            if (isset($errors['phone'])) {
                echo $errors['phone'];
            }
            ?>
        </label>
        <input id="phone" type="tel" name="phone" placeholder="Введите телефон" value="<?php echo $user->getPhone() ?>">

        <label for="email">E-mail</label>
        <label for="email" style="color: #4b1010">
            <?php
            if (isset($errors['email'])) {
                echo $errors['email'];
            }
            ?>
        </label>
        <input id="email" type="email" name="email" placeholder="Введите E-mail" value="<?php echo $user->getEmail() ?>">

        <label for="password">Пароль (Необязательно)</label>
        <input id="password" type="password" name="password" placeholder="Изменить пароль">

        <button type="submit" class="register-btn">Изменить</button>
    </form>
</div>
</body>
</html>