<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация и регистрация</title>
    <link rel="stylesheet" href="/css/signup.css">
</head>
<body>

<!-- Форма регистрации -->

<form action="" method="POST">
    <label for="name">Имя</label>
    <input id="name" type="text" name="name" placeholder="Введите имя">
    <label for="phone">Телефон</label>
    <input id="phone" type="tel" name="phone" placeholder="Введите телефон">
    <label for="email">E-mail</label>
    <input id="email" type="email" name="email" placeholder="Введите E-mail">
    <label for="password">Пароль</label>
    <input id="password" type="password" name="password" placeholder="Придумайте пароль">
    <label for="psw">Подтверждение пароля</label>
    <input id="psw" type="password" name="psw" placeholder="Повторите пароль">

    <button type="submit" class="register-btn">Зарегистрироваться</button>
    <p>
        У вас уже есть аккаунт? - <a href="/login">Авторизируйтесь</a>!
    </p>
</form>
</body>
</html>